<?php

/**
 * @file
 * Provides expanded entity APIs.
 */

use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function entity_theme() {
  return [
    'entity_add_list' => [
      'variables' => [
        'bundles' => [],
        'bundle_type' => NULL,
        'form_route_name' => NULL,
      ],
      'template' => 'entity-add-list',
    ],
  ];
}

/**
 * Prepares variables for the list of available bundles.
 *
 * Default template: entity-add-list.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - bundle_type: The entity type of the bundles.
 *   - bundles: An array of bundles.
 *   - form_route_name: The add form route.
 */
function template_preprocess_entity_add_list(&$variables) {
  $bundle_type = \Drupal::entityTypeManager()->getDefinition($variables['bundle_type']);
  $variables += [
    'class' => str_replace('_', '-', $bundle_type->getBundleOf()) . '-add-list',
    'create_bundle_url' => Url::fromRoute('entity.' . $bundle_type->id() . '.add_form'),
    'bundle_type_label' => $bundle_type->getLowercaseLabel(),
  ];

  foreach ($variables['bundles'] as $bundle) {
    $url = Url::fromRoute($variables['form_route_name'], [$bundle->getEntityTypeId() => $bundle->id()]);
    $variables['bundles'][$bundle->id()] = [
      'bundle' => $bundle->id(),
      'add_link' => \Drupal::l($bundle->label(), $url),
      'description' => [
        '#markup' => $bundle->getDescription(),
      ],
    ];
  }
}
